#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: pyproject
#
Name     : pypi-compreffor
Version  : 0.5.4
Release  : 15
URL      : https://files.pythonhosted.org/packages/22/a3/d02eac2052a1893c1dcc45e1d79fa09e9997a7de8df33acec1e3348569b5/compreffor-0.5.4.tar.gz
Source0  : https://files.pythonhosted.org/packages/22/a3/d02eac2052a1893c1dcc45e1d79fa09e9997a7de8df33acec1e3348569b5/compreffor-0.5.4.tar.gz
Summary  : A CFF subroutinizer for fontTools.
Group    : Development/Tools
License  : Apache-2.0 BSD-2-Clause
Requires: pypi-compreffor-bin = %{version}-%{release}
Requires: pypi-compreffor-license = %{version}-%{release}
Requires: pypi-compreffor-python = %{version}-%{release}
Requires: pypi-compreffor-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(cython)
BuildRequires : pypi(fonttools)
BuildRequires : pypi(py)
BuildRequires : pypi(setuptools)
BuildRequires : pypi(setuptools_git_ls_files)
BuildRequires : pypi(setuptools_scm)
BuildRequires : pypi(wheel)
BuildRequires : pypi-pluggy
BuildRequires : pypi-pytest
BuildRequires : pypi-tox
BuildRequires : pypi-virtualenv
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
|CI Build Status|
A CFF table subroutinizer for FontTools.
.. |CI Build Status| image:: https://github.com/googlefonts/compreffor/workflows/Build%20+%20Deploy/badge.svg
:target: https://github.com/googlefonts/compreffor/actions?query=workflow%3A%22Build+%2B+Deploy%22

%package bin
Summary: bin components for the pypi-compreffor package.
Group: Binaries
Requires: pypi-compreffor-license = %{version}-%{release}

%description bin
bin components for the pypi-compreffor package.


%package license
Summary: license components for the pypi-compreffor package.
Group: Default

%description license
license components for the pypi-compreffor package.


%package python
Summary: python components for the pypi-compreffor package.
Group: Default
Requires: pypi-compreffor-python3 = %{version}-%{release}

%description python
python components for the pypi-compreffor package.


%package python3
Summary: python3 components for the pypi-compreffor package.
Group: Default
Requires: python3-core
Provides: pypi(compreffor)
Requires: pypi(fonttools)

%description python3
python3 components for the pypi-compreffor package.


%prep
%setup -q -n compreffor-0.5.4
cd %{_builddir}/compreffor-0.5.4
pushd ..
cp -a compreffor-0.5.4 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1690210317
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FCFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export CXXFLAGS="$CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export MAKEFLAGS=%{?_smp_mflags}
python3 -m build --wheel --skip-dependency-check --no-isolation
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 -m build --wheel --skip-dependency-check --no-isolation

popd

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-compreffor
cp %{_builddir}/compreffor-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/pypi-compreffor/2b8b815229aa8a61e483fb4ba0588b8b6c491890 || :
cp %{_builddir}/compreffor-%{version}/src/cxx/mingw-std-threads/LICENSE %{buildroot}/usr/share/package-licenses/pypi-compreffor/dd7d2e4f4bde0bf9e83138927fc7df466377a015 || :
pip install --root=%{buildroot} --no-deps --ignore-installed dist/*.whl
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
pip install --root=%{buildroot}-v3 --no-deps --ignore-installed dist/*.whl
popd
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/compreffor

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-compreffor/2b8b815229aa8a61e483fb4ba0588b8b6c491890
/usr/share/package-licenses/pypi-compreffor/dd7d2e4f4bde0bf9e83138927fc7df466377a015

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/V3/usr/lib/python3*/*
/usr/lib/python3*/*
